In [51]:
import requests
import pandas as pd
from datetime import datetime
from google.transit import gtfs_realtime_pb2


URL = "https://realtime.gtfs.de/realtime-free.pb"

response = requests.get(URL, timeout=30)

In [52]:
def parse_gtfs_feed(response):
    """
    Parse a GTFS-RT response into a FeedMessage.

    Parameters
    ----------
    response : requests.Response
        HTTP response containing the serialized GTFS-RT feed.

    Returns
    -------
    FeedMessage
        Parsed GTFS-RT feed.
    """
    feed = gtfs_realtime_pb2.FeedMessage()
    feed.ParseFromString(response.content)

    print(f"Number of entities: {len(feed.entity)}")

    return feed

feed = parse_gtfs_feed(response)

Number of entities: 119102

In [53]:
for entity in feed.entity[:10]:
    print(entity)

id: "658155tu"
trip_update {
  trip {
    trip_id: "658155"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 0
    departure {
      delay: 0
      time: 1788611940
    }
    stop_id: "230052"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 1
    arrival {
      delay: 0
      time: 1788612060
    }
    departure {
      delay: 0
      time: 1788612060
    }
    stop_id: "528466"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 2
    arrival {
      delay: 0
      time: 1788612120
    }
    departure {
      delay: 0
      time: 1788612120
    }
    stop_id: "428151"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 3
    arrival {
      delay: 0
      time: 1788612180
    }
    departure {
      delay: 0
      time: 1788612180
    }
    stop_id: "108066"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 4
    arrival {
      delay: 0
      time: 1788612300
    }
    departure {
      delay: 0
      time: 1788612300
    }
    stop_id: "141024"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 5
    arrival {
      delay: 0
      time: 1788612360
    }
    departure {
      delay: 0
      time: 1788612360
    }
    stop_id: "374622"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 6
    arrival {
      delay: 0
      time: 1788612420
    }
    departure {
      delay: 0
      time: 1788612420
    }
    stop_id: "182259"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 7
    arrival {
      delay: 0
      time: 1788612480
    }
    departure {
      delay: 0
      time: 1788612480
    }
    stop_id: "358037"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 8
    arrival {
      delay: 0
      time: 1788612540
    }
    departure {
      delay: 0
      time: 1788612540
    }
    stop_id: "172772"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 9
    arrival {
      delay: 0
      time: 1788612600
    }
    departure {
      delay: 0
      time: 1788612600
    }
    stop_id: "473636"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 10
    arrival {
      delay: 0
      time: 1788612660
    }
    departure {
      delay: 0
      time: 1788612660
    }
    stop_id: "409408"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 11
    arrival {
      delay: 0
      time: 1788612720
    }
    departure {
      delay: 0
      time: 1788612720
    }
    stop_id: "118532"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 12
    arrival {
      delay: 0
      time: 1788612780
    }
    departure {
      delay: 0
      time: 1788612780
    }
    stop_id: "214573"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 13
    arrival {
      delay: -36
      time: 1788612864
    }
    departure {
      delay: -36
      time: 1788612864
    }
    stop_id: "348712"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 14
    arrival {
      delay: 25
      time: 1788612985
    }
    departure {
      delay: 25
      time: 1788612985
    }
    stop_id: "563634"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 15
    arrival {
      delay: 0
      time: 1788613080
    }
    departure {
      delay: 0
      time: 1788613080
    }
    stop_id: "196602"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 16
    arrival {
      delay: 0
      time: 1788613200
    }
    stop_id: "227227"
    schedule_relationship: SCHEDULED
  }
}

id: "841957tu"
trip_update {
  trip {
    trip_id: "841957"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 0
    departure {
      delay: 0
      time: 1788620760
    }
    stop_id: "525855"
    schedule_relationship: SCHEDULED
  }
}

id: "1527540tu"
trip_update {
  trip {
    trip_id: "1527540"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 0
    departure {
      delay: 95
      time: 1788607595
    }
    stop_id: "64027"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 1
    arrival {
      delay: 95
      time: 1788607655
    }
    departure {
      delay: 95
      time: 1788607655
    }
    stop_id: "496875"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 2
    arrival {
      delay: 95
      time: 1788607715
    }
    departure {
      delay: 95
      time: 1788607715
    }
    stop_id: "660380"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 3
    arrival {
      delay: 95
      time: 1788607835
    }
    departure {
      delay: 95
      time: 1788607835
    }
    stop_id: "121113"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 4
    arrival {
      delay: 95
      time: 1788607895
    }
    departure {
      delay: 95
      time: 1788607895
    }
    stop_id: "635183"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 5
    arrival {
      delay: 95
      time: 1788607955
    }
    departure {
      delay: 95
      time: 1788607955
    }
    stop_id: "384221"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 6
    arrival {
      delay: 95
      time: 1788608015
    }
    departure {
      delay: 95
      time: 1788608015
    }
    stop_id: "670837"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 7
    arrival {
      delay: 95
      time: 1788608135
    }
    departure {
      delay: 95
      time: 1788608135
    }
    stop_id: "225007"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 8
    arrival {
      delay: 95
      time: 1788608195
    }
    departure {
      delay: 95
      time: 1788608195
    }
    stop_id: "16253"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 9
    arrival {
      delay: 95
      time: 1788608255
    }
    departure {
      delay: 95
      time: 1788608255
    }
    stop_id: "643659"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 10
    arrival {
      delay: 95
      time: 1788608315
    }
    departure {
      delay: 95
      time: 1788608315
    }
    stop_id: "212530"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 11
    arrival {
      delay: 95
      time: 1788608435
    }
    departure {
      delay: 0
      time: 1788608460
    }
    stop_id: "678867"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 12
    arrival {
      delay: 0
      time: 1788608520
    }
    departure {
      delay: 0
      time: 1788608520
    }
    stop_id: "353189"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 13
    arrival {
      delay: 0
      time: 1788608580
    }
    departure {
      delay: 0
      time: 1788608580
    }
    stop_id: "672107"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 14
    arrival {
      delay: 0
      time: 1788608640
    }
    departure {
      delay: 0
      time: 1788608640
    }
    stop_id: "676415"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 15
    arrival {
      delay: 0
      time: 1788608700
    }
    departure {
      delay: 0
      time: 1788608700
    }
    stop_id: "687277"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 16
    arrival {
      delay: 0
      time: 1788608760
    }
    departure {
      delay: 0
      time: 1788608760
    }
    stop_id: "398979"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 17
    arrival {
      delay: 0
      time: 1788608820
    }
    departure {
      delay: 0
      time: 1788608820
    }
    stop_id: "327404"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 18
    arrival {
      delay: 0
      time: 1788608880
    }
    departure {
      delay: 0
      time: 1788608880
    }
    stop_id: "3201"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 19
    arrival {
      delay: 0
      time: 1788609000
    }
    departure {
      delay: 0
      time: 1788609000
    }
    stop_id: "52131"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 20
    arrival {
      delay: 0
      time: 1788609120
    }
    departure {
      delay: 0
      time: 1788609120
    }
    stop_id: "551155"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 21
    arrival {
      delay: 0
      time: 1788609180
    }
    departure {
      delay: 0
      time: 1788609180
    }
    stop_id: "619762"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 22
    arrival {
      delay: 0
      time: 1788609240
    }
    departure {
      delay: 0
      time: 1788609240
    }
    stop_id: "207614"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 23
    arrival {
      delay: 0
      time: 1788609300
    }
    departure {
      delay: 0
      time: 1788609300
    }
    stop_id: "651087"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 24
    arrival {
      delay: 0
      time: 1788609420
    }
    departure {
      delay: 0
      time: 1788609540
    }
    stop_id: "72979"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 25
    arrival {
      delay: 0
      time: 1788609600
    }
    departure {
      delay: 0
      time: 1788609600
    }
    stop_id: "342864"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 26
    arrival {
      delay: 0
      time: 1788609720
    }
    departure {
      delay: 0
      time: 1788609720
    }
    stop_id: "487403"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 27
    arrival {
      delay: 0
      time: 1788609780
    }
    departure {
      delay: 0
      time: 1788609780
    }
    stop_id: "402288"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 28
    arrival {
      delay: 0
      time: 1788609840
    }
    departure {
      delay: 0
      time: 1788609840
    }
    stop_id: "554866"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 29
    arrival {
      delay: 0
      time: 1788609960
    }
    departure {
      delay: 0
      time: 1788609960
    }
    stop_id: "287070"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 30
    arrival {
      delay: 0
      time: 1788610020
    }
    departure {
      delay: 0
      time: 1788610020
    }
    stop_id: "244070"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 31
    arrival {
      delay: 0
      time: 1788610080
    }
    stop_id: "152709"
    schedule_relationship: SCHEDULED
  }
}

id: "1638685tu"
trip_update {
  trip {
    trip_id: "1638685"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 0
    departure {
      delay: 0
      time: 1788616920
    }
    stop_id: "41940"
    schedule_relationship: SCHEDULED
  }
}

id: "1140698tu"
trip_update {
  trip {
    trip_id: "1140698"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 0
    departure {
      delay: 0
      time: 1788611520
    }
    stop_id: "282461"
    schedule_relationship: SCHEDULED
  }
}

id: "681172tu"
trip_update {
  trip {
    trip_id: "681172"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 0
    departure {
      delay: 0
      time: 1788610380
    }
    stop_id: "500777"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 1
    arrival {
      delay: 30
      time: 1788610470
    }
    departure {
      delay: 30
      time: 1788610470
    }
    stop_id: "75796"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 2
    arrival {
      delay: 30
      time: 1788610530
    }
    departure {
      delay: 30
      time: 1788610530
    }
    stop_id: "564941"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 3
    arrival {
      delay: 30
      time: 1788610650
    }
    departure {
      delay: 30
      time: 1788610650
    }
    stop_id: "264622"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 4
    arrival {
      delay: -30
      time: 1788610770
    }
    departure {
      delay: 30
      time: 1788610830
    }
    stop_id: "535641"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 5
    arrival {
      delay: 30
      time: 1788611010
    }
    departure {
      delay: 30
      time: 1788611010
    }
    stop_id: "59606"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 6
    arrival {
      delay: 30
      time: 1788611070
    }
    departure {
      delay: 30
      time: 1788611070
    }
    stop_id: "502355"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 7
    arrival {
      delay: 30
      time: 1788611130
    }
    departure {
      delay: 30
      time: 1788611130
    }
    stop_id: "108912"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 8
    arrival {
      delay: 30
      time: 1788611190
    }
    departure {
      delay: 30
      time: 1788611190
    }
    stop_id: "100527"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 9
    arrival {
      delay: 30
      time: 1788611250
    }
    departure {
      delay: 30
      time: 1788611250
    }
    stop_id: "537726"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 10
    arrival {
      delay: 30
      time: 1788611310
    }
    departure {
      delay: 30
      time: 1788611310
    }
    stop_id: "23158"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 11
    arrival {
      delay: 0
      time: 1788611400
    }
    stop_id: "13550"
    schedule_relationship: SCHEDULED
  }
}

id: "683359tu"
trip_update {
  trip {
    trip_id: "683359"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 0
    departure {
      delay: 0
      time: 1788604800
    }
    stop_id: "394796"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 1
    arrival {
      delay: 0
      time: 1788604860
    }
    departure {
      delay: 0
      time: 1788604860
    }
    stop_id: "145171"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 2
    arrival {
      delay: 0
      time: 1788604920
    }
    departure {
      delay: 0
      time: 1788604920
    }
    stop_id: "643237"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 3
    arrival {
      delay: 0
      time: 1788604980
    }
    departure {
      delay: 0
      time: 1788604980
    }
    stop_id: "296385"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 4
    arrival {
      delay: 0
      time: 1788605160
    }
    departure {
      delay: 0
      time: 1788605160
    }
    stop_id: "467446"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 5
    arrival {
      delay: 0
      time: 1788605340
    }
    departure {
      delay: 0
      time: 1788605340
    }
    stop_id: "352235"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 6
    arrival {
      delay: 0
      time: 1788605460
    }
    departure {
      delay: 0
      time: 1788605460
    }
    stop_id: "591869"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 7
    arrival {
      delay: 0
      time: 1788605700
    }
    departure {
      delay: 0
      time: 1788605700
    }
    stop_id: "342667"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 8
    arrival {
      delay: 0
      time: 1788605880
    }
    departure {
      delay: 0
      time: 1788605880
    }
    stop_id: "377973"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 9
    arrival {
      delay: 0
      time: 1788605940
    }
    departure {
      delay: 0
      time: 1788605940
    }
    stop_id: "649249"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 10
    arrival {
      delay: 0
      time: 1788606060
    }
    departure {
      delay: 0
      time: 1788606060
    }
    stop_id: "292621"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 11
    arrival {
      delay: 0
      time: 1788606240
    }
    stop_id: "628782"
    schedule_relationship: SCHEDULED
  }
}

id: "1453288tu"
trip_update {
  trip {
    trip_id: "1453288"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 0
    departure {
      delay: 0
      time: 1788610620
    }
    stop_id: "257813"
    schedule_relationship: SCHEDULED
  }
}

id: "225632tu"
trip_update {
  trip {
    trip_id: "225632"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 1
    arrival {
      delay: -22
      time: 1788608558
    }
    departure {
      delay: 0
      time: 1788608580
    }
    stop_id: "524631"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 2
    arrival {
      delay: -30
      time: 1788608670
    }
    departure {
      delay: 0
      time: 1788608700
    }
    stop_id: "503049"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 3
    arrival {
      delay: -24
      time: 1788608796
    }
    departure {
      delay: 0
      time: 1788608820
    }
    stop_id: "313146"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 4
    arrival {
      delay: -22
      time: 1788608918
    }
    departure {
      delay: 0
      time: 1788608940
    }
    stop_id: "515883"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 5
    arrival {
      delay: -21
      time: 1788608979
    }
    departure {
      delay: 0
      time: 1788609000
    }
    stop_id: "257987"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 6
    arrival {
      delay: -42
      time: 1788609138
    }
    departure {
      delay: 0
      time: 1788609180
    }
    stop_id: "425577"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 7
    arrival {
      delay: -33
      time: 1788609267
    }
    departure {
      delay: 0
      time: 1788609300
    }
    stop_id: "10221"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 8
    arrival {
      delay: -30
      time: 1788609390
    }
    departure {
      delay: 0
      time: 1788609420
    }
    stop_id: "314137"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 9
    arrival {
      delay: -24
      time: 1788609576
    }
    departure {
      delay: 0
      time: 1788609600
    }
    stop_id: "66369"
    schedule_relationship: SCHEDULED
  }
}

id: "1376364tu"
trip_update {
  trip {
    trip_id: "1376364"
    start_date: "20260905"
    schedule_relationship: SCHEDULED
  }
  stop_time_update {
    stop_sequence: 0
    departure {
      delay: 0
      time: 1788612300
    }

In [56]:
def parse_trip_updates(feed, stop_names, trip_lines):
    """
    Parse GTFS-RT trip updates into a pandas DataFrame.

    Parameters
    ----------
    feed : FeedMessage
        Parsed GTFS-RT feed containing trip updates.
    stop_names : dict
        Mapping from stop IDs to stop names.
    trip_lines : dict
        Mapping from trip IDs to line names.

    Returns
    -------
    pandas.DataFrame
        DataFrame containing trip, line, stop, arrival,
        departure, and delay information.
    """
    rows = []

    for entity in feed.entity:
        if not entity.HasField("trip_update"):
            continue

        trip = entity.trip_update.trip

        # Get line for this trip
        line = trip_lines.get(str(trip.trip_id))

        # Ignore trips that are not part of the selected agencies
        if line is None:
            continue

        for stop in entity.trip_update.stop_time_update:

            row = {
                "trip_id": trip.trip_id,
                "start_date": trip.start_date,
                "line": line,
                "stop_id": str(stop.stop_id),
                "stop_name": stop_names.get(str(stop.stop_id)),
                "stop_sequence": stop.stop_sequence,
            }

            if stop.HasField("departure"):
                row["departure_time"] = datetime.fromtimestamp(
                    stop.departure.time
                )
                row["departure_delay"] = stop.departure.delay

            if stop.HasField("arrival"):
                row["arrival_time"] = datetime.fromtimestamp(
                    stop.arrival.time
                )
                row["arrival_delay"] = stop.arrival.delay

            rows.append(row)

    return pd.DataFrame(rows)

In [57]:
def preprocess_gtfs(data_dir, munich_agencies):
    """
    Preprocess GTFS static data for selected agencies.

    Returns
    -------
    trip_lines : dict
        Mapping from trip_id to line name.

    stop_names : dict
        Mapping from stop_id to stop name.
    """

    routes_df = pd.read_csv(f"{data_dir}/routes.txt")
    trips_df = pd.read_csv(f"{data_dir}/trips.txt")
    stops_df = pd.read_csv(f"{data_dir}/stops.txt")

    routes_df["route_id"] = routes_df["route_id"].astype(str)
    routes_df["agency_id"] = routes_df["agency_id"].astype(str)

    trips_df["trip_id"] = trips_df["trip_id"].astype(str)
    trips_df["route_id"] = trips_df["route_id"].astype(str)

    stops_df["stop_id"] = stops_df["stop_id"].astype(str)

    munich_routes = routes_df[
        routes_df["agency_id"].isin(munich_agencies)
    ]

    route_lines = (
        munich_routes
        .set_index("route_id")["route_short_name"]
        .to_dict()
    )

    munich_trips = trips_df[
        trips_df["route_id"].isin(route_lines)
    ]

    trip_lines = (
        munich_trips
        .set_index("trip_id")["route_id"]
        .map(route_lines)
        .to_dict()
    )

    stop_names = (
        stops_df
        .set_index("stop_id")["stop_name"]
        .to_dict()
    )

    return trip_lines, stop_names

In [58]:
munich_agencies = ["100", "191", "364"]

trip_lines, stop_names = preprocess_gtfs(
    "../data",
    munich_agencies
)

In [59]:
df = parse_trip_updates(
    feed,
    stop_names,
    trip_lines
)

df.head(100)

,trip_id,start_date,line,stop_id,stop_name,stop_sequence,departure_time,departure_delay,arrival_time,arrival_delay
0,841957,20260905,U6,525855,"Colditz, Gewerbegebiet/anona",0,2026-09-05 17:06:00,0.0,NaT,NaN
1,1628519,20260905,63,583277,None,0,2026-09-05 13:35:00,0.0,NaT,NaN
2,1743480,20260905,271,568676,Leverkusen Mathildenhof Schöneberger Str.,0,2026-09-05 15:31:00,0.0,NaT,NaN
3,1845122,20260905,184,357527,"Ursberg, Gymnasium",0,2026-09-05 15:14:00,0.0,NaT,NaN
4,1845122,20260905,184,431872,Überl. Naturata,1,2026-09-05 15:15:00,0.0,2026-09-05 15:15:00,0.0
...,...,...,...,...,...,...,...,...,...,...
95,419240,20260905,190,478162,Burghausen Kapuzinergasse,29,2026-09-05 14:19:30,210.0,2026-09-05 14:19:30,210.0
96,419240,20260905,190,477055,Mettingen Cannstatter Str.,30,2026-09-05 14:20:30,210.0,2026-09-05 14:20:30,210.0
97,419240,20260905,190,79218,Bad Ems Pfingstwiese,31,2026-09-05 14:23:30,210.0,2026-09-05 14:23:30,210.0
98,419240,20260905,190,637126,"Bernburg Zickzackhausen, Richtung Sternzfeld",32,2026-09-05 14:26:30,210.0,2026-09-05 14:26:30,210.0
99,419240,20260905,190,409007,Goldbachstraße,33,2026-09-05 14:27:30,210.0,2026-09-05 14:27:30,210.0

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33090 entries, 0 to 33089
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   trip_id          33090 non-null  object
 1   start_date       33090 non-null  object
 2   line             33090 non-null  object
 3   stop_id          33090 non-null  object
 4   stop_name        32506 non-null  object
 5   stop_sequence    33090 non-null  int64
 6   departure_time   29699 non-null  datetime64[ns]
 7   departure_delay  29699 non-null  float64
 8   arrival_time     28882 non-null  datetime64[ns]
 9   arrival_delay    28882 non-null  float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(5)
memory usage: 2.5+ MB

In [61]:
def load_existing_realtime_data(
    parquet_path="../data/mvv_realtime.parquet"
):
    """
    Load existing MVV real-time data from a Parquet file.

    Parameters
    ----------
    parquet_path : str
        Path to the existing Parquet file.

    Returns
    -------
    pandas.DataFrame
        Existing MVV real-time data.
    """

    return pd.read_parquet(parquet_path)

In [62]:
def update_realtime_data(
    existing_df,
    new_df
):
    """
    Add new real-time data and keep the latest
    observation for each trip and stop.

    Parameters
    ----------
    existing_df : pandas.DataFrame
        Previously stored MVV real-time data.

    new_df : pandas.DataFrame
        Newly retrieved MVV real-time data.

    Returns
    -------
    pandas.DataFrame
        Updated MVV real-time data.
    """

    combined_df = pd.concat(
        [
            existing_df,
            new_df
        ],
        ignore_index=True
    )

    combined_df = (
        combined_df
        .drop_duplicates(
            subset=[
                "trip_id",
                "start_date",
                "stop_id"
            ],
            keep="last"
        )
        .reset_index(drop=True)
    )

    return combined_df

In [63]:
def save_realtime_data(
    realtime_df,
    parquet_path="../data/mvv_realtime.parquet"
):
    """
    Save MVV real-time data to a Parquet file.

    Parameters
    ----------
    realtime_df : pandas.DataFrame
        MVV real-time data to save.

    parquet_path : str
        Path where the Parquet file is stored.

    Returns
    -------
    None
        The DataFrame is saved to the specified Parquet file.
    """

    realtime_df.to_parquet(
        parquet_path,
        index=False
    )

In [64]:
existing_df = load_existing_realtime_data()

updated_df = update_realtime_data(
    existing_df,
    df
)

save_realtime_data(
    updated_df
)

In [65]:
existing_df = load_existing_realtime_data()

In [66]:
existing_df

,trip_id,start_date,line,stop_id,stop_name,stop_sequence,departure_time,departure_delay,arrival_time,arrival_delay
0,1192330,20260904,190,614970,August-Everding-Straße,1,2026-09-05 00:37:33,3.0,2026-09-05 00:37:33,3.0
1,1192330,20260904,190,576765,Sankt Pius,2,2026-09-05 00:37:48,-12.0,2026-09-05 00:37:48,-12.0
2,1192330,20260904,190,686743,Grafinger Straße,3,2026-09-05 00:39:22,-8.0,2026-09-05 00:38:52,-38.0
3,1192330,20260904,190,634241,Altöttinger Straße,4,2026-09-05 00:40:34,4.0,2026-09-05 00:40:11,-19.0
4,1192330,20260904,190,561261,Schlüsselbergstraße,5,2026-09-05 00:41:42,-18.0,2026-09-05 00:41:11,-49.0
...,...,...,...,...,...,...,...,...,...,...
49459,279582,20260905,822,196266,Holzkirchen,26,2026-09-05 13:22:34,-26.0,2026-09-05 13:22:22,-38.0
49460,279582,20260905,822,262947,Geroksruhe,27,2026-09-05 13:24:28,-32.0,2026-09-05 13:24:28,-32.0
49461,279582,20260905,822,151491,Donau-Arena,28,2026-09-05 13:27:46,46.0,2026-09-05 13:26:02,-58.0
49462,279582,20260905,822,443152,Limberg Gasthaus,29,2026-09-05 13:28:58,58.0,2026-09-05 13:28:42,42.0
49463,279582,20260905,822,413035,"Kirchwalsede, Schule, Mast 1",30,NaT,NaN,2026-09-05 13:30:32,32.0

In [67]:
existing_df.duplicated(
    subset=[
        "trip_id",
        "start_date",
        "stop_sequence"
    ]
).sum()

np.int64(3)